version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: menu-gen-db
    environment:
      POSTGRES_DB: menu_gen
      POSTGRES_USER: menu_user
      POSTGRES_PASSWORD: menu_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U menu_user -d menu_gen"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
